import StyleDictionary from 'style-dictionary';

/**
 * Custom format: emits a Tailwind v4 `@theme inline { ... }` block that maps
 * dsx semantic tokens to Tailwind's recognized namespaces
 * (--color-*, --radius-*, --text-*, --font-weight-*, --tracking-*, --leading-*).
 *
 * The output is meant to be `@import`ed from apps/gallery/app/globals.css *after*
 * `@import "tailwindcss";` and after the raw `tokens.css` is imported.
 */
StyleDictionary.registerFormat({
  name: 'tailwind/theme-inline',
  format: ({ dictionary }) => {
    const lines = [
      '/**',
      ' * Tailwind v4 @theme inline mapping for dsx tokens.',
      ' * Generated by Style Dictionary — do not edit.',
      ' */',
      '@theme inline {',
    ];

    const isSemanticColor = (t) =>
      t.path[0] === 'color' && t.path[1] !== 'scale' && t.path.length === 2;
    const isRadius = (t) => t.path[0] === 'radius';
    const isFontSize = (t) => t.path[0] === 'font' && t.path[1] === 'size';
    const isFontWeight = (t) => t.path[0] === 'font' && t.path[1] === 'weight';
    const isFontFamily = (t) => t.path[0] === 'font' && t.path[1] === 'family';
    const isTracking = (t) => t.path[0] === 'font' && t.path[1] === 'letterSpacing';
    const isLeading = (t) => t.path[0] === 'font' && t.path[1] === 'lineHeight';

    for (const token of dictionary.allTokens) {
      const name = token.name;
      if (isSemanticColor(token)) {
        lines.push(`  --color-${token.path[1]}: var(--${name});`);
      } else if (isRadius(token)) {
        lines.push(`  --radius-${token.path[1]}: var(--${name});`);
      } else if (isFontSize(token)) {
        lines.push(`  --text-${token.path[2]}: var(--${name});`);
      } else if (isFontWeight(token)) {
        lines.push(`  --font-weight-${token.path[2]}: var(--${name});`);
      } else if (isFontFamily(token)) {
        lines.push(`  --font-${token.path[2]}: var(--${name});`);
      } else if (isTracking(token)) {
        lines.push(`  --tracking-${token.path[2]}: var(--${name});`);
      } else if (isLeading(token)) {
        lines.push(`  --leading-${token.path[2]}: var(--${name});`);
      }
    }

    lines.push('  --color-background: var(--color-surface);');
    lines.push('  --color-foreground: var(--color-text);');
    lines.push('  --color-muted: var(--color-surface-muted);');
    lines.push('  --color-muted-foreground: var(--color-text-muted);');
    lines.push('  --color-ring: var(--color-focus-ring);');
    lines.push('  --radius: var(--radius-md);');
    lines.push('}\n');
    return lines.join('\n');
  },
});

const baseSource = ['tokens/core.tokens.json', 'tokens/semantic.tokens.json'];
const darkSource = ['tokens/core.tokens.json', 'tokens/themes/dark.tokens.json'];

// Mobile platforms get colors + dimensions only — font tokens (fontFamily arrays,
// composite typography) need platform-specific handling that the mobile ports
// will add when implementing. Web (CSS / Tailwind) gets everything.
const mobileFilter = (token) =>
  token.path[0] === 'color' || token.path[0] === 'spacing' || token.path[0] === 'radius';

const main = new StyleDictionary({
  source: baseSource,
  log: { warnings: 'disabled' },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { selector: ':root', outputReferences: true },
        },
      ],
    },
    tailwind: {
      transformGroup: 'css',
      buildPath: 'build/tailwind/',
      files: [
        {
          destination: 'theme.css',
          format: 'tailwind/theme-inline',
        },
      ],
    },
    flutter: {
      transformGroup: 'flutter',
      buildPath: 'build/flutter/',
      files: [
        {
          destination: 'Tokens.dart',
          format: 'flutter/class.dart',
          filter: mobileFilter,
          options: { className: 'HeliosTokens', showFileHeader: true },
        },
      ],
    },
    compose: {
      transformGroup: 'compose',
      buildPath: 'build/compose/',
      files: [
        {
          destination: 'Tokens.kt',
          format: 'compose/object',
          filter: mobileFilter,
          options: { className: 'HeliosTokens', packageName: 'com.helios.tokens' },
        },
      ],
    },
    ios: {
      transformGroup: 'ios-swift',
      buildPath: 'build/ios/',
      files: [
        {
          destination: 'Tokens.swift',
          format: 'ios-swift/class.swift',
          filter: mobileFilter,
          options: { className: 'HeliosTokens' },
        },
      ],
    },
  },
});

const dark = new StyleDictionary({
  source: darkSource,
  log: { warnings: 'disabled' },
  platforms: {
    cssDark: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [
        {
          destination: 'tokens.dark.css',
          format: 'css/variables',
          options: { selector: '.dark', outputReferences: false },
          filter: (token) => /themes\/dark\.tokens\.json$/.test(token.filePath ?? ''),
        },
      ],
    },
  },
});

await main.buildAllPlatforms();
await dark.buildAllPlatforms();
