/**
 * Generated by the chapter-2 smoke test (Phase 7).
 * Brief: "a pricing table with three tiers, monthly/annual toggle"
 * Reference: .dsx/page-references/pricing-tiered.stories.tsx (score 4)
 */
import type { Meta, StoryObj } from '@storybook/react-vite';
import { CheckIcon } from 'lucide-react';
import { Badge } from '@gallery/ui/badge';
import { Button } from '@gallery/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@gallery/ui/card';
import { Tabs, TabsList, TabsTrigger } from '@gallery/ui/tabs';

const meta = {
  title: 'Sections/Pricing — Three Tiers',
  parameters: { layout: 'centered' },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

const plans = [
  {
    name: 'Solo',
    price: '$0',
    period: 'forever',
    blurb: 'Everything you need for one project.',
    features: ['1 project', 'Unlimited issues', 'Keyboard shortcuts'],
    cta: 'Start free',
    variant: 'outline' as const,
  },
  {
    name: 'Team',
    price: '$19',
    period: '/ user / month',
    blurb: 'For small teams that ship together.',
    features: ['Unlimited projects', 'Shared inboxes', 'Email support', 'Branch experiments'],
    cta: 'Start 14-day trial',
    variant: 'default' as const,
    highlight: true,
  },
  {
    name: 'Studio',
    price: '$49',
    period: '/ user / month',
    blurb: 'For studios with 5+ active builds.',
    features: ['Everything in Team', 'SSO + audit log', 'Priority support', 'Custom integrations'],
    cta: 'Contact sales',
    variant: 'outline' as const,
  },
];

export const Default: Story = {
  render: () => (
    <div className="bg-background px-6 py-12 text-foreground">
      <div className="mx-auto max-w-5xl text-center">
        <h2 className="type-display">Pricing that grows with you.</h2>
        <p className="mt-2 type-body-md text-muted-foreground">
          Free forever for solo work. Upgrade when you collaborate.
        </p>
        <div className="mt-5 inline-block">
          <Tabs defaultValue="monthly">
            <TabsList>
              <TabsTrigger value="monthly">Monthly</TabsTrigger>
              <TabsTrigger value="annual">Annual (−20%)</TabsTrigger>
            </TabsList>
          </Tabs>
        </div>

        <div className="mt-8 grid gap-6 text-left sm:grid-cols-3">
          {plans.map((p) => (
            <Card key={p.name} className={p.highlight ? 'border-primary shadow-md' : ''}>
              <CardHeader>
                <div className="flex items-baseline justify-between">
                  <CardTitle>{p.name}</CardTitle>
                  {p.highlight && <Badge>Recommended</Badge>}
                </div>
                <CardDescription>{p.blurb}</CardDescription>
                <div className="mt-3 flex items-baseline gap-1">
                  <span className="type-headline-lg">{p.price}</span>
                  <span className="type-body-sm text-muted-foreground">{p.period}</span>
                </div>
              </CardHeader>
              <CardContent>
                <ul className="grid gap-2 type-body-sm">
                  {p.features.map((f) => (
                    <li key={f} className="flex items-start gap-2">
                      <CheckIcon className="mt-0.5 size-4 text-primary" />
                      <span>{f}</span>
                    </li>
                  ))}
                </ul>
                <Button variant={p.variant} className="mt-6 w-full">
                  {p.cta}
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  ),
};
