/**
 * Generated by the chapter-2 smoke test (Phase 7).
 * Brief: "modern SaaS landing page for a project management tool aimed at indie developers"
 * Reference: .dsx/page-references/landing-saas.stories.tsx (score 4)
 */
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ArrowRightIcon, CheckIcon, GitBranchIcon, InboxIcon, ZapIcon } from 'lucide-react';
import { Badge } from '@gallery/ui/badge';
import { Button } from '@gallery/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@gallery/ui/card';
import { Separator } from '@gallery/ui/separator';

const meta = {
  title: 'Pages/SaaS Landing',
  parameters: { layout: 'fullscreen' },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (
    <div className="min-h-screen bg-background text-foreground">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
        <div className="type-mono-sm">tasked.dev</div>
        <nav className="hidden gap-6 type-body-sm text-muted-foreground sm:flex">
          <a href="#features">Features</a>
          <a href="#integrations">Integrations</a>
          <a href="#pricing">Pricing</a>
        </nav>
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm">
            Sign in
          </Button>
          <Button size="sm">Start free</Button>
        </div>
      </header>

      <section className="mx-auto max-w-4xl px-6 py-12 text-center">
        <Badge variant="secondary" className="mb-4">
          Built for the solo and the small-team
        </Badge>
        <h1 className="type-display">Project management that gets out of your way.</h1>
        <p className="mx-auto mt-3 max-w-2xl type-body-md text-muted-foreground">
          Keyboard-first issue tracking, no Jira-style ceremony, no PM overhead. One inbox per
          project, branches for experiments, a daily digest that doesn't lie.
        </p>
        <div className="mt-5 flex flex-wrap justify-center gap-3">
          <Button size="lg">
            Start free <ArrowRightIcon />
          </Button>
          <Button size="lg" variant="outline">
            Watch the 90-second tour
          </Button>
        </div>
        <p className="mt-3 type-label-sm text-muted-foreground">
          Free for solo. No credit card. Self-host if you'd rather.
        </p>
      </section>

      <Separator />

      <section id="features" className="mx-auto max-w-6xl px-6 py-20">
        <div className="grid gap-6 sm:grid-cols-3">
          {[
            {
              icon: InboxIcon,
              title: 'One inbox per project',
              body: 'Issues, comments, mentions, status changes — all in one stream you can clear in a coffee.',
            },
            {
              icon: GitBranchIcon,
              title: 'Branches for experiments',
              body: 'Fork a project, try a re-org, merge or discard. No data loss, no scary archive screen.',
            },
            {
              icon: ZapIcon,
              title: 'Keyboard-first everything',
              body: 'Every action under three keystrokes. Mouse use is opt-in, never required.',
            },
          ].map((f) => (
            <Card key={f.title}>
              <CardHeader>
                <f.icon className="text-primary" />
                <CardTitle className="mt-2 type-title-md">{f.title}</CardTitle>
              </CardHeader>
              <CardContent className="type-body-sm text-muted-foreground">{f.body}</CardContent>
            </Card>
          ))}
        </div>
      </section>

      <Separator />

      <section className="mx-auto max-w-3xl px-6 py-20 text-center">
        <p className="type-mono-sm uppercase text-muted-foreground">
          Used by builders shipping alone
        </p>
        <div className="mt-4 flex flex-wrap justify-center gap-x-8 gap-y-3 type-body-sm text-muted-foreground">
          <span>Lea V.</span>
          <span>Marcus O.</span>
          <span>Priya R.</span>
          <span>Tom K.</span>
          <span>Sofia D.</span>
        </div>
      </section>

      <section className="bg-muted py-20">
        <div className="mx-auto flex max-w-3xl flex-col items-center gap-4 px-6 text-center">
          <h2 className="type-headline-lg">Start in 30 seconds.</h2>
          <p className="type-body-md text-muted-foreground">
            Sign up with email or GitHub. First project free forever.
          </p>
          <div className="mt-2 flex flex-wrap items-center justify-center gap-x-4 gap-y-2 type-body-sm">
            <span className="inline-flex items-center gap-1.5">
              <CheckIcon className="size-4 text-primary" /> No credit card
            </span>
            <span className="inline-flex items-center gap-1.5">
              <CheckIcon className="size-4 text-primary" /> Self-host or hosted
            </span>
            <span className="inline-flex items-center gap-1.5">
              <CheckIcon className="size-4 text-primary" /> Cancel anytime
            </span>
          </div>
          <Button size="lg">Get started free</Button>
        </div>
      </section>
    </div>
  ),
};
